<?php

function random_forum_user_menu() {
    $items['random_forum_user/test'] = array (
        'title' => 'Test Page',
        'description' => 'Test description text',
        'page callback' => 'drupal_get_form',
        'page arguments' => array('random_forum_user_simple_form'),
        'access callback' => TRUE,
    );
    return $items;
}

function random_forum_user_simple_form($form, &$form_submit) {
    $form['color'] = array(
        '#title' => t('Favorite color'),
        '#type' => 'textfield',
        '#required' => TRUE,
        '#description' => t('What is your favorite color?'),
    );
    $form['submit'] = array(
        '#type' => 'submit',
        '#value' => 'Submit',
    );
    return $form;
}

function random_forum_user_form_node_form_alter(&$form, &$form_state) {

    $type = $form['#node']->type;

    if ($type == 'forum') {

        $path_to_module = drupal_get_path('module','random_forum_user');

        require($path_to_module.'/phpMudnames/mudnames.php');

        $mudPath = $path_to_module.'/phpMudnames';

        $gname = Mudnames::getInstance($mudPath. '/data/');

        $mudFile = 'female-1';
        $mudName = $gname->generate_name_from($mudFile);

        $form['author']['use_random_user'] = array(
            '#type' => 'checkbox',
            '#title' => t('Use this random username'),
            '#ajax' => array(
                'callback' => 'random_forum_user_add_and_update_user',
                'wrapper' => 'edit-name-dlg',
            ),
        );

        $form['author']['note_to_change_name_first'] = array(
            '#markup' => t('IF YOU EDIT THE RANDOM, NAME DO IT
            <span style="text-decoration: underline"><b>BEFORE</b></span> CLICKING THIS'),
        );

        $form['author']['current_random_user'] = array(
            '#type' => 'textfield',
            '#title' => t('Random User Name'),
            '#default_value' => t($mudName),
        );

        $form['author']['name']['#prefix'] = '<div id="edit-name-dlg">';
        $form['author']['name']['#suffix'] = '</div>';

        $useRandomUserName = !empty($form_state['values']['use_random_user']) ?
            $form_state['values']['use_random_user'] : 0 ;

        if ($useRandomUserName == 1) {
            $form['author']['name']['#value'] = $form_state['values']['current_random_user'];

            $random_name = $form_state['values']['current_random_user'];

            $edit = array(
                'name' => $random_name,
                'pass' => 'blah',//user_password(),
                'mail' => $random_name . '@localhost',
                'status' => 1,
//                'language' => 'en',
//                'roles' => array(2 => 'authenticated_user'),
            );

            user_save(NULL,$edit);
        }

        if ($useRandomUserName == 0) {
            $form['author']['name']['#value'] = $form['author']['name']['#default_value'];
        }
    }

}

function random_forum_user_add_and_update_user($form, &$form_state) {



    return $form['author']['name'];
}